test:
  S3_BUCKET_NAME: "artolution"
  AWS_ACCESS_KEY_ID: "AKIAIHDHIWDQKC7GED6A"
  AWS_SECRET_ACCESS_KEY: "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"
  FACEBOOK_ID: "134796040319330"
  FACEBOOK_SECRET: "d2d82c3989586620d496524c074bee8e"

development:
  S3_BUCKET_NAME: "artolution"
  AWS_ACCESS_KEY_ID: "AKIAIHDHIWDQKC7GED6A"
  AWS_SECRET_ACCESS_KEY: "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"
  FACEBOOK_ID: "134796040319330"
  FACEBOOK_SECRET: "d2d82c3989586620d496524c074bee8e"

production:
  S3_BUCKET_NAME: "artolution"
  AWS_ACCESS_KEY_ID: "AKIAIHDHIWDQKC7GED6A"
  AWS_SECRET_ACCESS_KEY: "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"
  FACEBOOK_ID: "134796040319330"
  FACEBOOK_SECRET: "d2d82c3989586620d496524c074bee8e"
