test:
  S3_BUCKET_NAME: "artolution"
  AWS_ACCESS_KEY_ID: "AKIAIHDHIWDQKC7GED6A"
  AWS_SECRET_ACCESS_KEY: "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"

development:
  S3_BUCKET_NAME: "artolution"
  AWS_ACCESS_KEY_ID: "AKIAIHDHIWDQKC7GED6A"
  AWS_SECRET_ACCESS_KEY: "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"

production:
  S3_BUCKET_NAME: "artolution"
  AWS_ACCESS_KEY_ID: "AKIAIHDHIWDQKC7GED6A"
  AWS_SECRET_ACCESS_KEY: "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"
