# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ea40db2357b0c60f6ed7de72041c1b89a5e0a034521ff65f37d990b9ca941484ffbdb9030c7dd6934ef5e2bdfd14aef0e535f198651c13b37b0f4244b08b526

test:
  secret_key_base: 462d342bb10e14cda36cfe50fbcd1605acc2a3e55e0833973c36917dbbbeef372dee41326edb024eb102952666d8a90d908f84446b288505ccf6dc1455a8c17f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
